2025-06-28 19:59:23,700 INFO    MainThread:14008 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-28 19:59:23,700 INFO    MainThread:14008 [wandb_setup.py:_flush():81] Configure stats pid to 14008
2025-06-28 19:59:23,700 INFO    MainThread:14008 [wandb_setup.py:_flush():81] Loading settings from C:\Users\Paolo\.config\wandb\settings
2025-06-28 19:59:23,701 INFO    MainThread:14008 [wandb_setup.py:_flush():81] Loading settings from C:\Polimi\Master\2Sem\ACA_GraphML_Project\kaggle_optuna_project\wandb\settings
2025-06-28 19:59:23,701 INFO    MainThread:14008 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-28 19:59:23,701 INFO    MainThread:14008 [wandb_init.py:setup_run_log_directory():703] Logging user logs to C:\Polimi\Master\2Sem\ACA_GraphML_Project\kaggle_optuna_project\wandb\run-20250628_195923-6cxudjpd\logs\debug.log
2025-06-28 19:59:23,701 INFO    MainThread:14008 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to C:\Polimi\Master\2Sem\ACA_GraphML_Project\kaggle_optuna_project\wandb\run-20250628_195923-6cxudjpd\logs\debug-internal.log
2025-06-28 19:59:23,702 INFO    MainThread:14008 [wandb_init.py:init():831] calling init triggers
2025-06-28 19:59:23,702 INFO    MainThread:14008 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'use_augmentation': False, 'add_self_loops': True, 'normalize_features': True, 'add_random_walk_pe': False, 'use_dim_reduction': False, 'explained_variance_ratio': 0.8528818292014123, 'gnn_type': 'GCN', 'hidden_dim': 128, 'num_layers': 5, 'dropout': 0.06974693032602092, 'use_residual': False, 'use_layer_norm': False, 'pooling_type': 'set2set', 'processing_steps': 1, 'regressor_type': 'deep_mlp', 'regressor_hidden_dims': [32, 16], 'regressor_activation': 'swish', 'regressor_dropout': 0.017194260557609198, 'batch_size': 64, 'learning_rate': 5.4880470007660426e-05, 'optimizer': 'adam', 'weight_decay': 0.003795853142670641, 'scheduler': 'plateau', '_wandb': {}}
2025-06-28 19:59:23,702 INFO    MainThread:14008 [wandb_init.py:init():872] starting backend
2025-06-28 19:59:24,250 INFO    MainThread:14008 [wandb_init.py:init():875] sending inform_init request
2025-06-28 19:59:24,277 INFO    MainThread:14008 [wandb_init.py:init():883] backend started and connected
2025-06-28 19:59:24,281 INFO    MainThread:14008 [wandb_init.py:init():956] updated telemetry
2025-06-28 19:59:24,327 WARNING MsgRouterThr:14008 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Polimi\Master\2Sem\ACA_GraphML_Project\.conda\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Polimi\Master\2Sem\ACA_GraphML_Project\.conda\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Polimi\Master\2Sem\ACA_GraphML_Project\.conda\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Polimi\Master\2Sem\ACA_GraphML_Project\.conda\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Polimi\Master\2Sem\ACA_GraphML_Project\.conda\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Polimi\Master\2Sem\ACA_GraphML_Project\.conda\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-28 19:59:24,347 INFO    MainThread:14008 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-28 19:59:24,358 INFO    MsgRouterThr:14008 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
